### PR TITLE
Fix chrome prefs

### PR DESCRIPTION
**Pull request by stof**
refs https://github.com/FriendsOfBehat/MinkExtension/pull/2#issuecomment-769025610

### CODE REVIEW

**Comment by Yozhef** [comment]
@stof looks good but please upgrade to master to run ci process

**Comment by stof** [comment]
@Yozhef done.

**Comment by stof** [comment]
@Yozhef do you have an ETA for tagging a release ?

Also, side note, it would be great to enable the issue tracker on this repo (and other FriendsOfBehat repos if needed), to avoid that issues get reported to the Behat or Mink repositories

**Comment by Yozhef** [comment]
@stof I have the rights for the release, I will do it soon.
I do not have rights to the issue tracker on this repo account (

**Comment by Yozhef** [comment]
@stof done 2.7.1

**Comment by stof** [comment]
@Yozhef thanks

**Pull request merged**
